FROM kong:3.7

USER root

# Instale ferramentas de build
RUN apt-get update && apt-get install -y \
    build-essential \
    libpcre3-dev \
    luarocks \
    gcc \
    libssl-dev \
    git \
    unzip \
    curl \
    make

# Limpa o cache do luarocks
RUN rm -rf /root/.cache/luarocks /var/cache/luarocks

# Instale lua-cjson
RUN git clone https://github.com/openresty/lua-cjson.git /tmp/lua-cjson && \
    cd /tmp/lua-cjson && \
    luarocks make && \
    rm -rf /tmp/lua-cjson

# Instale lua-resty-openssl
RUN git clone https://github.com/fffonion/lua-resty-openssl.git /tmp/lua-resty-openssl && \
    cd /tmp/lua-resty-openssl && \
    luarocks make && \
    rm -rf /tmp/lua-resty-openssl

# Instale lua-resty-hmac
RUN git clone https://github.com/jkeys089/lua-resty-hmac.git /tmp/lua-resty-hmac && \
    cd /tmp/lua-resty-hmac && \
    luarocks make && \
    cp lib/resty/hmac.lua /usr/local/share/lua/5.1/resty/hmac.lua && \
    rm -rf /tmp/lua-resty-hmac

# Instale lua-resty-jwt
RUN git clone https://github.com/cdbattags/lua-resty-jwt.git /tmp/lua-resty-jwt && \
    cd /tmp/lua-resty-jwt && \
    mkdir -p third-party/lua-resty-hmac/lib/resty && \
    cp /usr/local/share/lua/5.1/resty/hmac.lua third-party/lua-resty-hmac/lib/resty/ && \
    luarocks make && \
    rm -rf /tmp/lua-resty-jwt

# Copie o plugin para dentro do container
COPY kong /usr/local/share/lua/5.1/kong

# Corrija permissões
RUN chown -R kong:kong /usr/local/share/lua/5.1/kong

USER kong